### ISSUE TITLE
Game Crashing mid-load

### ISSUE THREAD

**Issue by Tangeld3** [Y0ungSandwich/Mech-Magic-Lite#1]
I'm not entirely sure whether this is an issue with my computer or an issue of the mods in the pack not playing together nicely somehow, but every time I attempt to load the pack, it crashes during initialization. Log of one such incident provided below.
https://paste.atlauncher.com/view/2195cfe8

**Comment by Y0ungSandwich** [comment]
Try updating your graphics drivers.

**Comment by Tangeld3** [comment]
So this is a graphics issue, then? Shame, my graphics drivers are up to date...
